import { Fund } from "@/components/portfolio/types";

export const sampleFunds: Fund[] = [
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    category: "Stocks",
    currentPrice: 181.3,
    currency: "USD",
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corp.",
    category: "Stocks",
    currentPrice: 380.1,
    currency: "USD",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc.",
    category: "Stocks",
    currentPrice: 154.7,
    currency: "USD",
  },
  {
    ticker: "AMZN",
    name: "Amazon.com, Inc.",
    category: "Stocks",
    currentPrice: 204.8,
    currency: "USD",
  },
  {
    ticker: "NVDA",
    name: "NVIDIA Corp.",
    category: "Stocks",
    currentPrice: 122.1,
    currency: "USD",
  },
  {
    ticker: "BTC",
    name: "Bitcoin",
    category: "Crypto",
    currentPrice: 68500,
    currency: "USD",
  },
  {
    ticker: "ETH",
    name: "Ethereum",
    category: "Crypto",
    currentPrice: 3400,
    currency: "USD",
  },
  {
    ticker: "SOL",
    name: "Solana",
    category: "Crypto",
    currentPrice: 130.5,
    currency: "USD",
  },
  {
    ticker: "TSLA",
    name: "Tesla, Inc.",
    category: "Stocks",
    currentPrice: 252.1,
    currency: "USD",
  },
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    category: "ETFs",
    currentPrice: 457.7,
    currency: "USD",
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
    category: "ETFs",
    currentPrice: 380.2,
    currency: "USD",
  },
  {
    ticker: "VFIAX",
    name: "Vanguard 500 Index Fund",
    category: "Mutual Funds",
    currentPrice: 410.7,
    currency: "USD",
  },
  {
    ticker: "VTSAX",
    name: "Vanguard Total Stock Market",
    category: "Mutual Funds",
    currentPrice: 110.4,
    currency: "USD",
  },
  {
    ticker: "GLD",
    name: "SPDR Gold Shares",
    category: "ETFs",
    currentPrice: 189.3,
    currency: "USD",
  },
  {
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    category: "ETFs",
    currentPrice: 182.2,
    currency: "USD",
  },
  {
    ticker: "NIFTY",
    name: "Nifty 50 Index Fund",
    category: "Mutual Funds",
    currentPrice: 2100,
    currency: "INR",
  },
  {
    ticker: "HDFCFW",
    name: "HDFC Prudence Fund",
    category: "Mutual Funds",
    currentPrice: 47.2,
    currency: "INR",
  },
  {
    ticker: "BANKNIFTY",
    name: "Bank Nifty Options",
    category: "Options",
    currentPrice: 38200,
    currency: "INR",
  },
  {
    ticker: "AAMIF",
    name: "Aditya Birla MIP",
    category: "Mutual Funds",
    currentPrice: 12.8,
    currency: "INR",
  },
  {
    ticker: "ARKK",
    name: "ARK Innovation ETF",
    category: "ETFs",
    currentPrice: 60.3,
    currency: "USD",
  },
];
